### ISSUE TITLE
[BUG]: error in admin user change for the default users [Axels]

### ISSUE THREAD

**Issue by MitanOmar** [adfinis/timed#219]
### Description

when trying to edit the users in Django admins, i am able to edit all users except (Axels) <- the dev setup data

### Steps to Reproduce

login to django admin
try edit the user axels <- from the default dev setup
![Screenshot from 2024-05-27 10-13-03](https://github.com/adfinis/timed/assets/22119228/130539fd-5035-4de4-a5f4-39b6db39c367)

### Expected Behavior

i should be able to edit all users via django admin

### Version

4.1.7

### Required

- [X] I have checked past issues to see if this bug has already been reported.

**Comment by c0rydoras** [comment]
What exactly were you trying to edit?

**Comment by MitanOmar** [comment]
there is only one user that i can not edit him, the user with number 2, it's one of the default users for the dev env setup

**Comment by c0rydoras** [comment]
Can you add screenshots of how it should look?

**Comment by tk0e** [comment]
Hi @c0rydoras and @MitanOmar 

I now get a Server Error (500) regardless of which user I'd like to open in Django.

Examples:
https://timed.adfinis.com/admin/employment/user/406/change/
https://timed.adfinis.com/admin/employment/user/204/change/

This makes it a relatively critical bug, since it blocks our backoffice from time-critical modifications.

Cheers
